version: "3.8"

services:

  publisher-agent:
    container_name: publisher
    hostname: publisher
    build:
      context: .
    volumes:
      - ./src:/publisher-agent/src
    environment:
      - PROTOCOL=AMQP # Must be set to AMQP or MQTT
      - AMQP_QUEUE_HOST=rmq0
      - MQTT_QUEUE_HOST=mosquitto
      - TOPIC=/5jggokgpepnvsb2uv4s40d59ov/tag001/attrs
    ports:
      - 8053:8053