version: "3.3"

networks:
   default:
      external:
         name: syntheticnet

services:
  publisher-agent:
    container_name: publisher
    hostname: publisher
    build:
      context: .
    restart: always
    environment:
      - PROTOCOL=AMQP # Must be set to AMQP or MQTT
      - AMQP_QUEUE_HOST=rmq0
      - MQTT_QUEUE_HOST=mosquitto
    ports:
      - 8053:8053
